# Use the latest Ubuntu as the base image
FROM ubuntu

# Update and upgrade APT
RUN apt-get update && apt-get upgrade -y

# Set the command to echo "Hello, World!" when the container runs
CMD ["echo", "Hello, World!"]
